#!/bin/bash
#
# chkconfig: 35 90 12
# description: cbot server
# cbot daemon init script
#

. /etc/init.d/functions

# start cbotd
start() {

    daemon /usr/local/sbin/cbot --config /etc/cbot.conf --daemon &
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/cbotd
    success $"cbotd server startup"
    return $RETVAL
}

# stop cbotd
stop() {

    killproc cbot
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/cbotd
    return $RETVAL
}

#### control logic ####
case "$1" in 
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status cbot
        ;;
    restart|reload|condrestart)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        RETVAL=1
esac
exit $RETVAL
